### ISSUE TITLE
libcurl.so

### ISSUE THREAD

**Issue by YanMario** [mrtazz/restclient-cpp#152] opened 2020-03-17 03:20 UTC
librestclient-cpp.so：对‘curl_easy_perform’未定义的引用
librestclient-cpp.so：对‘curl_easy_getinfo’未定义的引用
librestclient-cpp.so：对‘curl_easy_reset’未定义的引用

**Comment by mrtazz** [comment] 2020-03-17 17:20
can you please add some context around what the problem is and what error message you're seeing in English?

**Comment by mrtazz** [comment] 2020-03-18 18:47
Closing this for lack of details about the problem. Please feel free to reopen if you can provide more information.

**Closed by mrtazz** 2020-03-18 18:47 UTC

**Comment by YanMario** [comment] 2020-03-22 14:55
Ok,Thank you, I resolve it.


| |
13279406510
|
|
13279406510@163.com
|
签名由网易邮箱大师定制


On 03/19/2020 02:47，Daniel Schauenberg<notifications@github.com> wrote：

Closing this for lack of details about the problem. Please feel free to reopen if you can provide more information.
