### ISSUE TITLE
Undefined reference to `RestClient::get(std::string const&)'

### ISSUE THREAD

**Issue by JorricksTU** [mrtazz/restclient-cpp#56] opened 2016-07-26 18:18 UTC
Hello,

So I installed all the files using the configure, make and make install commands.
Now when I use the example I get the following error:
Undefined reference to `RestClient::get(std::string const&)`.
Do you have any idea how to fix this?

**Comment by mrtazz** [comment] 2016-07-26 20:40
this looks like a duplicate of https://github.com/mrtazz/restclient-cpp/issues/55, closing this in favor of the existing issue. If it's not the same one, please reopen.

**Comment by mrtazz** [comment] 2016-07-26 20:49
On closer inspection this is most likely not the same issue. Can you provide your platform and environment details and the output log of the failed compilation please?

**Comment by msofyanqusyairi** [comment] 2016-08-02 16:32
i have the same problem. i used on raspberry pi

**Comment by mrtazz** [comment] 2016-08-03 02:23
Did you install it into the default location as root? Have you run `/sbin/ldconfig` after installation?

**Comment by gosantos** [comment] 2016-08-09 15:03
I am facing a similar issue with this lib. I've got this error:

**main.cpp:(.text+0x64): undefined reference to `RestClient::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'**

I have used this link to setup the lib: 

[](https://packagecloud.io/mrtazz/restclient-cpp/packages/ubuntu/trusty/restclient-cpp_0.4.4-1_amd64.deb)

G++ and Ubuntu version:
**g++ (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609**

**Comment by gosantos** [comment] 2016-08-09 15:14
I tested the restclient using the terminal and it worked, so it seems to be just an issue with the reference. Should I have to export some global variable?

**Comment by mrtazz** [comment] 2016-08-11 18:53
@gosantos can you provide the test program that throws this error on compilation?

**Comment by gosantos** [comment] 2016-08-11 20:10
@mrtazz I recompiled the lib from source and now I've got the same error:

**main.cpp:(.text+0x45): undefined reference to `RestClient::get(std::string const&)'**

My code is very simple:

```
#include "restclient-cpp/restclient.h"

int main(){

  RestClient::Response r = RestClient::get("http://ip.jsontest.com/?callback=showMyIP");

  return 0;
}

```

**Comment by mrtazz** [comment] 2016-08-14 15:04
@gosantos thanks! can you also provide the command with which you compiled the test program?

**Comment by gosantos** [comment] 2016-08-14 16:19
@mrtazz yes, ofc. I am using **g++ main.cpp -o main**
Btw I have ran the command   **/sbin/ldconfig** and it didn't work as well;

**Comment by mrtazz** [comment] 2016-08-15 00:35
You have to tell it to link the shared library in as well. Something like `g++ main.cpp -o main -L /path/to/restclient-cpp-so/ -l librestclient -lcurl`

**Comment by mrtazz** [comment] 2016-11-28 02:29
closing this issue. Please reopen if the problem persists.

**Closed by mrtazz** 2016-11-28 02:29 UTC

**Comment by kiyology** [comment] 2017-06-15 12:59
@mrtazz I'm having this issue too. i used `-L /usr/local/include/restclient-cpp/  /usr/local/lib/librestclient-cpp.so  /usr/lib/x86_64-linux-gnu/libcurl.a` and I'm getting  
`c++: warning: /usr/local/lib/librestclient-cpp.so: linker input file unused because linking not done
c++: warning: /usr/lib/x86_64-linux-gnu/libcurl.a: linker input file unused because linking not done
[100%] Linking CXX executable testing
CMakeFiles/testing/testing.o: In function `main':
/home/xxxxxx/testing.cpp:1088: undefined reference to `RestClient::get(std::string const&)'
collect2: error: ld returned 1 exit status
`
Any idea how to solve this? Been debugging all day long. Thanks!

**Comment by dwburke** [comment] 2017-06-15 13:20
@kiyology 
iirc I think you want to do 

`-L /usr/local/lib -lrestclient-cpp`

**Comment by kiyology** [comment] 2017-06-16 01:04
@mrtazz still having the same issue. after trying `-L /usr/local/lib  -lrestclient-cpp -lcurl` 
saying `undefined reference to `RestClient::get(std::string const&)'` during linking.

**Comment by chshaiiith** [comment] 2017-07-05 20:14
Hi @mrtazz, I have been facing with compiling the simple code. I am getting 
============================
some.cpp:(.text+0x57): undefined reference to `RestClient::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
============================

To compile the code I am using : g++ -L /usr/local/lib -lrestclient-cpp -lcurl  some.cpp 
==================================================
Also my code looks like :
#include "restclient-cpp/restclient.h"
#include <vector>
#include <ctime>
#include<iostream>
#include <string>

using namespace std;

int main() {
    RestClient::Response r = RestClient::get("http://localhost:8080/get_logs/1/2");
    return 0;
}

========================
For installation , I have used 
>  git clone https://github.com/mrtazz/restclient-cpp.git
>  cd restclient-cpp
>  ./autogen.sh
> ./configure
> make install

Kindly let me know what I did wrong ? Any help would be good ! :)

**Comment by mrtazz** [comment] 2017-07-06 02:14
do you have the headers in your include path like `-I /usr/local/include`?

**Comment by rakhack** [comment] 2017-07-16 13:54
`undefined reference to RestClient::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'`

Tried installing your lib via every method I found, still doesn't work.

Header files included, include path told to the compiler; `-L /usr/local/lib/` and `-lrestclient-cpp` passed to linker, all files ARE in that directory.

`ldconfig -p` shows that  **ld**  sees the library, and ***ar*** with ***objdump*** show that such symbols are in the file...

Even tried moving the files between `usr/lb` and `usr/local/lib`, renaming them with or without the `-` symbol...
I've been working on it all day, idk what else to do.

Here's what is passed to the compiler:
`g++ tests/tests_all.cpp -std=c++1z -pthread -Iinclude/ -Ilibs/ -L /usr/local/lib/ -L../build -o tests/tests_all -lrestclient-cpp -lcurl -lgtest build/libao3.a`

**Comment by rakhack** [comment] 2017-07-16 17:07
Well, sorry for the mess, figured out I should never forget there's no evil magic when working with code.
The problem was on my side, and quite common, I must say, and it was about linking order.

I use GNU Make, and my **makefile** has the following line:
`TEST_LIBRARIES=$(LIBRARIES) $(OUT) -lgtest`, where **$(OUT)** was the static library I made with `make build` and **$(LIBRARIES)** == `-lrestclient-cpp`

I got confused and for some reason didn't realize that not only the executable, but also the library in $(OUT) depended on the restclient lib. Well, I realized, but didn't pay much attention to it. So, it was all about linking order, №0 solution on StackExchange. :man_facepalming: 

My bad, sorry again.
Your library is awesome :trophy: :+1:

**Comment by mrtazz** [comment] 2017-07-18 14:25
@rakhack Thanks! Glad you found a fix :)

**Comment by NibrassHaider** [comment] 2018-05-24 16:34
Anyone can help me for the following problema please 
build/Debug/Cygwin-Windows/main.o: In function `MinHeap<std::string>::insert(int, std::string)':
/cygdrive/c/Users/nibrass/Documents/NetBeansProjects/P3_Ex1/MinHeap.h:85: undefined reference to `NodeMinHeap<std::string>::NodeMinHeap(NodeMinHeap<std::string> const&)'
 when i click on the error , it takes me to my class MinHeap in a method insert where i creat a node type of NodeMinHeap i don't know where i am getting wrong, please help me .
![image](https://user-images.githubusercontent.com/25898445/40499031-011a2afe-5f81-11e8-8cb5-c0d15c03524e.png)

**Comment by KevinIsSun** [comment] 2018-10-24 03:33
Sorry, I still get this error. And I have tried all methods mentioned above.

I install this lib by download deb file in `https://packagecloud.io/mrtazz/restclient-cpp`, and use `sudo dpkg -i xxx.deb` to install.

After install, i found header files in /usr/include, and so file in /usr/lib/. Then I run `sudo ldconfig`.
my code:
```
#include "restclient-cpp/restclient.h"
#include <iostream>
#include <string>

int main() {
    std::string url = "http://baidu.com";
    RestClient::Response r = RestClient::get(url);

    std::cout << r.code << "\n";
    return 0;
}
```
I run `g++ -I /usr/include/ -L /usr/lib/ -lrestclient-cpp -lcurl test_restclient.cc` to compile.
Then I get error message:
```
/tmp/ccCejkeS.o: In function `main':
test_restclient.cc:(.text+0x66): undefined reference to `RestClient::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
```

I have no idea how to fix it. It make me so sad.

**Comment by raaka1** [comment] 2019-08-31 20:51
g++ main.cpp -o main -I /home/smartcow/restclient-cpp/include/ -L /usr/local/lib/librestclient-cpp.so -lcurl -L /usr/local/lib -lrestclient-cpp
