### ISSUE TITLE
Can we have fluent API for new Requests

### ISSUE THREAD

**Issue by sumeetchhetri** [mrtazz/restclient-cpp#112] opened 2018-11-01 06:01 UTC
So the code can actually look like, 

```
// get a connection object
RestClient::Connection* conn = new RestClient::Connection("http://url.com");
// configure basic auth
conn->SetBasicAuth("WarMachine68", "WARMACHINEROX")->SetTimeout(5)->SetUserAgent("foo/cool")->FollowRedirects(true);
```

**Comment by mrtazz** [comment] 2019-12-04 11:01
what's the advantage of changing the API? I'm not opposed to it if this would improve the project. However in my experience fluid APIs are more likely to make the code more complicated, obscure failure and return paths, and add overhead in debugging.

I'm closing this since the issue is fairly old already and hasn't seen any activity. But feel free to reopen if you're still interested in having a discussion about it.

**Closed by mrtazz** 2019-12-04 11:01 UTC
