### ISSUE TITLE
Includes Error

### ISSUE THREAD

**Issue by Spottimus** [mrtazz/restclient-cpp#15] opened 2015-01-10 13:25 UTC
- I had errors while trying to start using restclient-cpp within my own project due to missing includes. These are all the includes required to work for me.

```
#include <libcurl\curl.h>
#include <string>
#include <map>
#include <cstdlib>
#include "meta.h"
#include <algorithm>
#include <iostream>
#include <functional>
#include <locale>
#include <numeric>
#include <cctype>
```

**Comment by salehi** [comment] 2015-03-22 21:50
You have to give more information about the error in order to we can understand what is your problem.
paste the output in a paste service or Gist and link it here.

**Comment by mrtazz** [comment] 2015-03-25 12:34
I second what @salehi said. Could you please provide more information about what the problem is here? A gist of example code and the error would be great.

**Comment by salehi** [comment] 2015-05-10 19:42
@mrtazz Forget it, I just suggested him to be better reporter :)

**Comment by mrtazz** [comment] 2015-08-09 22:05
Closing this for now. If the problem persists, please reopen with a more detailed error description and some debug output.

**Closed by mrtazz** 2015-08-09 22:05 UTC
